"""
FastAPI backend: serves predictions and dataset stats to the Next.js dashboard.

Usage:
    uvicorn api.main:app --reload --port 8000   (run from project root)

Endpoints:
    GET  /health
    GET  /stats
    GET  /metrics
    GET  /metrics/classification
    GET  /feature-importance
    GET  /simulate/tv-sweep
    POST /predict         : best model only
    POST /predict/all     : all models (for simulator comparison)
    POST /classify        : campaign performance classification
    POST /optimize        : inverse prediction (budget → target sales)
    POST /probability     : RF uncertainty / P(sales ≥ goal)
"""
import sys
import json
import pickle
import joblib
import numpy as np
import pandas as pd
from pathlib import Path
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "src"))

from preprocessing import (load_data, get_feature_names,
                            NUMERIC_FEATURES, CATEGORICAL_FEATURES, TARGET_REG)

# ── App state (loaded once at startup) ───────────────────────────────────────
state: dict = {}


@asynccontextmanager
async def lifespan(app: FastAPI):
    # ── Regression models (full sklearn Pipelines) ────────────────────────────
    with open(ROOT / "models" / "model_list.json") as f:
        model_names = json.load(f)
    state["models"] = {
        n: joblib.load(ROOT / "models" / f"{n}.pkl") for n in model_names
    }

    # Train/test split (saved by src/train.py)
    with open(ROOT / "models" / "splits.pkl", "rb") as f:
        state["splits"] = pickle.load(f)

    # Cross-validation results
    with open(ROOT / "models" / "cv_results.json") as f:
        state["cv"] = json.load(f)

    # Full dataset for /stats
    df = load_data()
    df["Total_Budget"] = df[NUMERIC_FEATURES].sum(axis=1)
    df["ROI"]          = df[TARGET_REG] / df["Total_Budget"]
    state["df"] = df

    # Sales quantiles for performance classification fallback
    q33, q66 = df[TARGET_REG].quantile([1 / 3, 2 / 3])
    state["sales_q33"] = float(q33)
    state["sales_q66"] = float(q66)

    # ── Classification models (separate preprocessor + estimators) ───────────
    _clf_pipe = ROOT / "models" / "pipeline_classification.pkl"
    _clf_le   = ROOT / "models" / "label_encoder.pkl"
    if _clf_pipe.exists() and _clf_le.exists():
        state["clf_preprocessor"]  = joblib.load(_clf_pipe)
        state["clf_label_encoder"] = joblib.load(_clf_le)
        clf_models = {}
        for name in ["random_forest", "gradient_boosting", "logistic_regression", "mlp"]:
            p = ROOT / "models" / f"{name}_classification.pkl"
            if p.exists():
                clf_models[name] = joblib.load(p)
        state["clf_models"] = clf_models
    else:
        state["clf_models"] = {}

    # Classification metrics CSV
    _clf_csv = ROOT / "models" / "metrics_classification.csv"
    if _clf_csv.exists():
        df_clf = pd.read_csv(_clf_csv)
        # Normalise column order
        cols = [c for c in ["Model", "Accuracy", "F1-macro", "ROC-AUC"] if c in df_clf.columns]
        df_clf = df_clf[cols]
        state["clf_metrics"] = df_clf.to_dict("records")
    else:
        state["clf_metrics"] = []

    # Validation vs Test metrics CSV (generated by src/evaluate.py)
    _vt_csv = ROOT / "models" / "metrics_val_test.csv"
    if _vt_csv.exists():
        state["val_test_metrics"] = pd.read_csv(_vt_csv).to_dict("records")
    else:
        state["val_test_metrics"] = []

    # Pre-compute expensive caches
    _build_metrics_cache()
    _build_feature_importance_cache()

    yield
    state.clear()


def _build_metrics_cache():
    X_test = state["splits"]["X_test"]
    y_test = state["splits"]["y_test"]
    cv     = state["cv"]
    rows   = []
    for name, pipeline in state["models"].items():
        y_pred = pipeline.predict(X_test)
        rows.append({
            "name":        name,
            "label":       name.replace("_", " ").title(),
            "r2":          round(float(r2_score(y_test, y_pred)), 4),
            "rmse":        round(float(np.sqrt(mean_squared_error(y_test, y_pred))), 4),
            "mae":         round(float(mean_absolute_error(y_test, y_pred)), 4),
            "cv_r2_mean":  cv.get(name, {}).get("mean", 0),
            "cv_r2_std":   cv.get(name, {}).get("std",  0),
        })
    state["metrics"] = sorted(rows, key=lambda x: x["r2"], reverse=True)


def _build_feature_importance_cache():
    preferred = ["gradient_boosting", "random_forest"]
    target    = next((n for n in preferred if n in state["models"]), None)
    if target is None:
        state["feature_importance"] = {}
        return
    pipeline    = state["models"][target]
    feat_names  = get_feature_names(pipeline.named_steps["preprocessor"])
    importances = pipeline.named_steps["model"].feature_importances_
    state["feature_importance"] = {
        "model": target,
        "features": sorted(
            [{"feature": fn, "importance": round(float(imp), 4)}
             for fn, imp in zip(feat_names, importances)],
            key=lambda x: x["importance"], reverse=True,
        ),
    }


# ── FastAPI app ───────────────────────────────────────────────────────────────
app = FastAPI(title="Marketing ROI API", version="1.0.0", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve evaluation figures (generated by src/evaluate.py)
_figures_dir = ROOT / "figures"
if _figures_dir.exists():
    app.mount("/figures", StaticFiles(directory=str(_figures_dir)), name="figures")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _best_reg_model() -> str:
    preferred = ["gradient_boosting", "random_forest", "linear_regression", "mlp"]
    name = next((n for n in preferred if n in state["models"]), None)
    if name is None:
        raise HTTPException(status_code=503, detail="No regression models loaded")
    return name


def _build_input(req: "PredictRequest") -> pd.DataFrame:
    return pd.DataFrame([{
        "TV":           req.TV,
        "Radio":        req.Radio,
        "Social Media": req.Social_Media,
        "Influencer":   req.Influencer,
    }])


# ── Endpoints ─────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    return {
        "status": "ok",
        "models_loaded": list(state.get("models", {}).keys()),
        "clf_models_loaded": list(state.get("clf_models", {}).keys()),
    }


@app.get("/stats")
def stats():
    df: pd.DataFrame = state["df"]

    counts, edges = np.histogram(df[TARGET_REG].dropna(), bins=20)
    sales_dist = [
        {"range": f"{int(edges[i])}-{int(edges[i+1])}", "count": int(c)}
        for i, c in enumerate(counts)
    ]
    budget_breakdown = {col: round(float(df[col].mean()), 2) for col in NUMERIC_FEATURES}
    by_inf           = df.groupby("Influencer")[[TARGET_REG, "ROI"]].mean().round(2)
    correlations     = {col: round(float(df[col].corr(df[TARGET_REG])), 4)
                        for col in NUMERIC_FEATURES}

    return {
        "total_campaigns":    int(len(df)),
        "avg_sales":          round(float(df[TARGET_REG].mean()), 2),
        "avg_roi":            round(float(df["ROI"].mean()), 4),
        "avg_total_budget":   round(float(df["Total_Budget"].mean()), 2),
        "best_channel":       max(correlations, key=correlations.get),
        "sales_distribution": sales_dist,
        "budget_breakdown":   budget_breakdown,
        "sales_by_influencer": by_inf[TARGET_REG].to_dict(),
        "roi_by_influencer":  by_inf["ROI"].to_dict(),
        "correlations":       correlations,
        "sales_q33":          round(state["sales_q33"], 2),
        "sales_q66":          round(state["sales_q66"], 2),
    }


def _safe(v: float, decimals: int = 4) -> float:
    """Return rounded float, replacing NaN/Inf with 0.0 for JSON safety."""
    try:
        f = float(v)
        return 0.0 if (f != f or f == float("inf") or f == float("-inf")) else round(f, decimals)
    except (TypeError, ValueError):
        return 0.0


@app.get("/analytics")
def analytics():
    df: pd.DataFrame = state["df"]
    features = ["TV", "Radio", "Social Media"]
    all_cols  = features + [TARGET_REG]

    # ── Per-feature statistics ────────────────────────────────────────────────
    feat_stats: dict = {}
    for col in all_cols:
        s = df[col].dropna()
        q1, q3 = float(s.quantile(0.25)), float(s.quantile(0.75))
        iqr = q3 - q1
        lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr
        outliers = s[(s < lower) | (s > upper)]
        feat_stats[col] = {
            "mean":          _safe(s.mean(), 2),
            "median":        _safe(s.median(), 2),
            "std":           _safe(s.std(), 2),
            "min":           _safe(s.min(), 2),
            "max":           _safe(s.max(), 2),
            "q1":            _safe(q1, 2),
            "q3":            _safe(q3, 2),
            "iqr":           _safe(iqr, 2),
            "skewness":      _safe(s.skew(), 4),
            "kurtosis":      _safe(s.kurt(), 4),
            "outlier_count": int(len(outliers)),
            "outlier_pct":   _safe(len(outliers) / len(s) * 100, 2),
            "whisker_low":   _safe(max(s.min(), lower), 2),
            "whisker_high":  _safe(min(s.max(), upper), 2),
        }

    # ── Histograms (25 bins each) ─────────────────────────────────────────────
    histograms: dict = {}
    for col in all_cols:
        s = df[col].dropna()
        counts, edges = np.histogram(s, bins=25)
        histograms[col] = [
            {
                "bin_start": round(float(edges[i]), 2),
                "bin_end":   round(float(edges[i + 1]), 2),
                "count":     int(counts[i]),
                "midpoint":  round(float((edges[i] + edges[i + 1]) / 2), 2),
            }
            for i in range(len(counts))
        ]

    # ── Scatter sample (≤ 500 points) ────────────────────────────────────────
    samp = df.sample(min(500, len(df)), random_state=42)
    scatter_sample = [
        {
            "tv":         _safe(r["TV"], 2),
            "radio":      _safe(r["Radio"], 2),
            "social":     _safe(r["Social Media"], 2),
            "sales":      _safe(r[TARGET_REG], 2),
            "influencer": str(r["Influencer"]),
        }
        for _, r in samp.iterrows()
    ]

    # ── Sales by influencer: box stats ───────────────────────────────────────
    sales_by_inf: dict = {}
    for inf, grp in df.groupby("Influencer"):
        s = grp[TARGET_REG].dropna()
        q1i, q3i = float(s.quantile(0.25)), float(s.quantile(0.75))
        iqri = q3i - q1i
        sales_by_inf[str(inf)] = {
            "min":          _safe(s.min(), 2),
            "q1":           _safe(q1i, 2),
            "median":       _safe(s.median(), 2),
            "mean":         _safe(s.mean(), 2),
            "q3":           _safe(q3i, 2),
            "max":          _safe(s.max(), 2),
            "std":          _safe(s.std(), 2),
            "count":        int(len(s)),
            "whisker_low":  _safe(max(s.min(), q1i - 1.5 * iqri), 2),
            "whisker_high": _safe(min(s.max(), q3i + 1.5 * iqri), 2),
        }

    # ── Class distribution ────────────────────────────────────────────────────
    if "perf_class" in df.columns:
        class_dist = {str(k): int(v) for k, v in df["perf_class"].value_counts().items()}
    else:
        q33, q66 = state["sales_q33"], state["sales_q66"]
        class_dist = {
            "High":   int((df[TARGET_REG] >= q66).sum()),
            "Medium": int(((df[TARGET_REG] >= q33) & (df[TARGET_REG] < q66)).sum()),
            "Low":    int((df[TARGET_REG] < q33).sum()),
        }

    # ── Pairwise correlations (upper triangle) ────────────────────────────────
    pairwise: dict = {}
    for i, c1 in enumerate(all_cols):
        for j, c2 in enumerate(all_cols):
            if i < j:
                pairwise[f"{c1}|{c2}"] = _safe(df[c1].corr(df[c2]), 4)

    return {
        "feature_stats":           feat_stats,
        "histograms":              histograms,
        "scatter_sample":          scatter_sample,
        "sales_by_influencer_box": sales_by_inf,
        "class_distribution":      class_dist,
        "pairwise_correlations":   pairwise,
        "total_campaigns":         int(len(df)),
    }


@app.get("/metrics")
def metrics():
    return {"models": state["metrics"]}


@app.get("/metrics/classification")
def metrics_classification():
    return {"models": state.get("clf_metrics", [])}


@app.get("/metrics/val-test")
def metrics_val_test():
    return {"models": state.get("val_test_metrics", [])}


@app.get("/feature-importance")
def feature_importance():
    return state.get("feature_importance", {})


# ── Simulate TV sweep ─────────────────────────────────────────────────────────

@app.get("/simulate/tv-sweep")
def tv_sweep(
    radio:      float = Query(20.0, ge=0),
    sm:         float = Query(5.0,  ge=0),
    influencer: str   = Query("Mega"),
    steps:      int   = Query(60,   ge=10, le=200),
):
    if influencer not in ("Mega", "Macro", "Micro", "Nano"):
        raise HTTPException(status_code=422, detail="Invalid Influencer value")

    model_name = _best_reg_model()
    pipeline   = state["models"][model_name]
    tv_values  = np.linspace(0, 300, steps)

    results = []
    for tv in tv_values:
        X    = pd.DataFrame([{"TV": float(tv), "Radio": radio,
                               "Social Media": sm, "Influencer": influencer}])
        pred = float(pipeline.predict(X)[0])
        results.append({"tv": round(float(tv), 1), "sales": round(pred, 2)})

    return {
        "data":          results,
        "model":         model_name,
        "training_max_tv": 297.0,
        "current_radio": radio,
        "current_sm":    sm,
        "influencer":    influencer,
    }


# ── Prediction ────────────────────────────────────────────────────────────────

class PredictRequest(BaseModel):
    TV:           float = Field(..., ge=0, le=500)
    Radio:        float = Field(..., ge=0, le=200)
    Social_Media: float = Field(..., ge=0, le=50)
    Influencer:   str   = Field(...)

    model_config = {
        "json_schema_extra": {
            "example": {"TV": 50, "Radio": 20, "Social_Media": 5, "Influencer": "Mega"}
        }
    }


@app.post("/predict")
def predict(req: PredictRequest):
    if req.Influencer not in ("Mega", "Macro", "Micro", "Nano"):
        raise HTTPException(status_code=422, detail="Invalid Influencer value")

    model_name   = _best_reg_model()
    pred         = float(state["models"][model_name].predict(_build_input(req))[0])
    total_budget = req.TV + req.Radio + req.Social_Media
    avg_sales    = float(state["df"][TARGET_REG].mean())

    return {
        "predicted_sales": round(pred, 2),
        "roi":             round(pred / total_budget, 4) if total_budget > 0 else 0.0,
        "total_budget":    round(total_budget, 2),
        "vs_average":      round(pred - avg_sales, 2),
        "model_used":      model_name,
    }


@app.post("/predict/all")
def predict_all(req: PredictRequest):
    if req.Influencer not in ("Mega", "Macro", "Micro", "Nano"):
        raise HTTPException(status_code=422, detail="Invalid Influencer value")

    X_in  = _build_input(req)
    total = req.TV + req.Radio + req.Social_Media
    return {
        "predictions": [
            {
                "model":           name,
                "label":           name.replace("_", " ").title(),
                "predicted_sales": round(float(pipeline.predict(X_in)[0]), 2),
                "roi":             round(float(pipeline.predict(X_in)[0]) / total, 4)
                                   if total > 0 else 0.0,
            }
            for name, pipeline in state["models"].items()
        ]
    }


# ── Classification ────────────────────────────────────────────────────────────

@app.post("/classify")
def classify(req: PredictRequest):
    if req.Influencer not in ("Mega", "Macro", "Micro", "Nano"):
        raise HTTPException(status_code=422, detail="Invalid Influencer value")

    clf_models = state.get("clf_models", {})
    clf_pre    = state.get("clf_preprocessor")
    clf_le     = state.get("clf_label_encoder")

    if clf_models and clf_pre and clf_le:
        # Use the best available classification model
        model = (clf_models.get("random_forest")
                 or clf_models.get("gradient_boosting")
                 or next(iter(clf_models.values())))
        X  = _build_input(req)
        Xt = clf_pre.transform(X)
        pred  = model.predict(Xt)[0]
        proba = float(model.predict_proba(Xt)[0].max())
        label = clf_le.inverse_transform([pred])[0]
    else:
        # Fallback: classify by sales quantile thresholds
        model_name = _best_reg_model()
        sales = float(state["models"][model_name].predict(_build_input(req))[0])
        if sales >= state["sales_q66"]:
            label, proba = "High",   0.80
        elif sales >= state["sales_q33"]:
            label, proba = "Medium", 0.65
        else:
            label, proba = "Low",    0.75

    return {"label": label, "confidence": round(proba, 4)}


# ── Inverse prediction (optimize budget → target sales) ───────────────────────

class OptimizeRequest(BaseModel):
    target_sales: float = Field(..., gt=0)
    max_budget:   float = Field(400.0, gt=0)
    influencer:   str   = Field("Macro")


@app.post("/optimize")
def optimize(req: OptimizeRequest):
    from scipy.optimize import minimize

    if req.influencer not in ("Mega", "Macro", "Micro", "Nano"):
        raise HTTPException(status_code=422, detail="Invalid Influencer value")

    model_name = _best_reg_model()
    pipeline   = state["models"][model_name]
    inf        = req.influencer

    def objective(x):
        tv, radio, sm = float(x[0]), float(x[1]), float(x[2])
        X    = pd.DataFrame([{"TV": tv, "Radio": radio, "Social Media": sm, "Influencer": inf}])
        pred = float(pipeline.predict(X)[0])
        return (pred - req.target_sales) ** 2

    df = state["df"]
    x0      = [df["TV"].median(), df["Radio"].median(), df["Social Media"].median()]
    bounds  = [(0, 500), (0, 200), (0, 50)]
    cons    = [{"type": "ineq", "fun": lambda x: req.max_budget - float(x[0]+x[1]+x[2])}]

    result  = minimize(objective, x0, method="SLSQP",
                       bounds=bounds, constraints=cons,
                       options={"maxiter": 500, "ftol": 1e-8})

    opt_tv, opt_radio, opt_sm = [round(float(v), 2) for v in result.x]
    X_opt   = pd.DataFrame([{"TV": opt_tv, "Radio": opt_radio,
                              "Social Media": opt_sm, "Influencer": inf}])
    opt_pred  = round(float(pipeline.predict(X_opt)[0]), 2)
    opt_total = round(opt_tv + opt_radio + opt_sm, 2)
    opt_roi   = round((opt_pred - opt_total) / opt_total * 100, 2) if opt_total > 0 else 0.0

    return {
        "TV":             opt_tv,
        "Radio":          opt_radio,
        "Social_Media":   opt_sm,
        "total_budget":   opt_total,
        "projected_sales": opt_pred,
        "roi":            opt_roi,
        "gap":            round(opt_pred - req.target_sales, 2),
        "model_used":     model_name,
        "converged":      bool(result.success),
    }


# ── RF uncertainty / probability analysis ────────────────────────────────────

class ProbabilityRequest(BaseModel):
    TV:           float = Field(..., ge=0)
    Radio:        float = Field(..., ge=0)
    Social_Media: float = Field(..., ge=0)
    Influencer:   str   = Field(...)
    goal:         float = Field(..., gt=0)


@app.post("/probability")
def probability(req: ProbabilityRequest):
    if req.Influencer not in ("Mega", "Macro", "Micro", "Nano"):
        raise HTTPException(status_code=422, detail="Invalid Influencer value")

    rf = state["models"].get("random_forest")
    if rf is None or not hasattr(rf.named_steps.get("model", object()), "estimators_"):
        raise HTTPException(status_code=503, detail="Random Forest model not available")

    X          = _build_input(PredictRequest(
        TV=req.TV, Radio=req.Radio, Social_Media=req.Social_Media, Influencer=req.Influencer
    ))
    rf_model   = rf.named_steps["model"]
    preprocessor = rf.named_steps["preprocessor"]
    Xt         = preprocessor.transform(X)

    tree_preds = np.array([tree.predict(Xt)[0] for tree in rf_model.estimators_])
    mean_pred  = float(np.mean(tree_preds))
    std_pred   = float(np.std(tree_preds))
    prob_hit   = float(np.mean(tree_preds >= req.goal))

    # Build histogram buckets for the frontend (40 bins)
    counts, edges = np.histogram(tree_preds, bins=40)
    histogram = [
        {
            "range":    round(float(edges[i]), 1),
            "count":    int(counts[i]),
            "above_goal": bool(edges[i] >= req.goal),
        }
        for i in range(len(counts))
    ]

    return {
        "mean":            round(mean_pred, 2),
        "std":             round(std_pred, 2),
        "min":             round(float(tree_preds.min()), 2),
        "max":             round(float(tree_preds.max()), 2),
        "probability_goal": round(prob_hit, 4),
        "n_trees":         len(tree_preds),
        "histogram":       histogram,
        "goal":            req.goal,
    }
